import { ExampleProblem } from '../types/signal';

/**
 * Pre-defined example problems for quick testing
 */
export const exampleProblems: ExampleProblem[] = [
    {
        id: 'ex1',
        name: 'Window Function',
        description: 'Unit step window: u(n+2) - u(n-1)',
        signal: 'u(n+2) - u(n-1)',
        operation: { type: 'none', parameters: {} },
        nMin: -5,
        nMax: 5,
    },
    {
        id: 'ex2',
        name: 'Shifted Impulse',
        description: 'Impulse at n=3: d(n-3)',
        signal: 'd(n-3)',
        operation: { type: 'none', parameters: {} },
        nMin: -2,
        nMax: 8,
    },
    {
        id: 'ex3',
        name: 'Time Shift Example',
        description: 'Shift ramp right by 2: y(n) = r(n-2)',
        signal: 'r(n)',
        operation: { type: 'shift', parameters: { k: 2 } },
        nMin: -3,
        nMax: 7,
    },
    {
        id: 'ex4',
        name: 'Folding Example',
        description: 'Reflect exponential: y(n) = x(-n) where x(n) = 0.8^n × u(n)',
        signal: '0.8^n * u(n)',
        operation: { type: 'fold', parameters: {} },
        nMin: -5,
        nMax: 5,
    },
    {
        id: 'ex5',
        name: 'Time Scaling (Compression)',
        description: 'Compress by 2×: y(n) = x(2n) where x(n) = u(n+4) - u(n-4)',
        signal: 'u(n+4) - u(n-4)',
        operation: { type: 'scale', parameters: { mu: 2 } },
        nMin: -5,
        nMax: 5,
    },
    {
        id: 'ex6',
        name: 'Complex Composition: x(-n-2)',
        description: 'Fold and shift: y(n) = x(-n-2) where x(n) = u(n) - u(n-3)',
        signal: 'u(n) - u(n-3)',
        operation: { type: 'compose', parameters: { expression: '-n-2' } },
        nMin: -6,
        nMax: 6,
    },
    {
        id: 'ex7',
        name: 'Complex Composition: x(-2n+4)',
        description: 'Combined operations: y(n) = x(-2n+4) where x(n) = r(n) × u(n) - r(n-5) × u(n-5)',
        signal: 'r(n)*u(n) - r(n-5)*u(n-5)',
        operation: { type: 'compose', parameters: { expression: '-2*n+4' } },
        nMin: -2,
        nMax: 8,
    },
    {
        id: 'ex8',
        name: 'Exponential Decay',
        description: 'Decaying exponential: x(n) = 0.7^n × u(n)',
        signal: '0.7^n * u(n)',
        operation: { type: 'none', parameters: {} },
        nMin: -2,
        nMax: 10,
    },
    {
        id: 'ex9',
        name: 'Triangular Pulse',
        description: 'Triangle using ramps: x(n) = r(n+3) - 2×r(n) + r(n-3)',
        signal: 'r(n+3) - 2*r(n) + r(n-3)',
        operation: { type: 'none', parameters: {} },
        nMin: -5,
        nMax: 5,
    },
    {
        id: 'ex10',
        name: 'Soal: x(n) - Signal Asli',
        description: 'x(n)={-n, -2≤n≤-1; n-1, 0≤n≤3; 0, lainnya}',
        signal: '(-n) * (u(n+2) - u(n)) + (n-1) * (u(n) - u(n-4))',
        operation: { type: 'none', parameters: {} },
        nMin: -4,
        nMax: 5,
    },
    {
        id: 'ex11',
        name: 'Soal: y(n) = x(-n-2)',
        description: 'Transformasi: Flip (cermin) lalu geser kiri 2. y(n) = x(-n-2)',
        signal: '(-n) * (u(n+2) - u(n)) + (n-1) * (u(n) - u(n-4))',
        operation: { type: 'compose', parameters: { expression: '-n-2' } },
        nMin: -5,
        nMax: 2,
    },
    {
        id: 'ex12',
        name: 'Soal: y(n) = x(-2n+4)',
        description: 'Transformasi: Kompresi 2x, flip, geser kanan 2. y(n) = x(-2n+4)',
        signal: '(-n) * (u(n+2) - u(n)) + (n-1) * (u(n) - u(n-4))',
        operation: { type: 'compose', parameters: { expression: '-2*n+4' } },
        nMin: -1,
        nMax: 4,
    },
    {
        id: 'ex13',
        name: 'Soal 2: Even/Odd Decomposition',
        description: 'Dekomposisi sinyal menjadi komponen genap xₑ(n) dan ganjil xₒ(n). x(-2)=2, x(-1)=1, x(0)=1, x(2)=1, x(4)=2',
        signal: '2*d(n+2) + d(n+1) + d(n) + d(n-2) + 2*d(n-4)',
        operation: { type: 'decompose', parameters: {} },
        nMin: -4,
        nMax: 4,
    },
];
